//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CutNFood.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_cart()
        {
            this.tbl_cartItem = new HashSet<tbl_cartItem>();
        }
    
        public int cart_id { get; set; }
        public Nullable<decimal> totalPrice { get; set; }
        public Nullable<int> user_id { get; set; }
        public bool isCheckOut { get; set; }
    
        public virtual tbl_account tbl_account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cartItem> tbl_cartItem { get; set; }
    }
}
