//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CutNFood.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_account()
        {
            this.tbl_cart = new HashSet<tbl_cart>();
        }
    
        public int user_id { get; set; }
        public string username { get; set; }
        public Nullable<int> userType_id { get; set; }
        public string password { get; set; }
        public string email { get; set; }
    
        public virtual tbl_userType tbl_userType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cart> tbl_cart { get; set; }
    }
}
